platform :ios, '8.0'
use_frameworks!

target 'OAuthManager' do
  # Pods for OauthManager
  pod 'OAuthSwift', '~> 0.5.2'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        target.build_settings(configuration.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

        target.build_settings(configuration.name)['EMBEDDED_CONTENT_CONTAINS_SWIFT'] = 'YES'
        target.build_settings(configuration.name)['ENABLE_BITCODE'] = 'NO'
        target.build_settings(configuration.name)['MACH_O_TYPE'] = 'mh_dylib'
        target.build_settings(configuration.name)['OTHER_LDFLAGS'] = '$(inherited)'

        target.build_settings(configuration.name)['USER_HEADER_SEARCH_PATHS'] = "$(BUILT_PRODUCTS_DIR)"
        target.build_settings(configuration.name)['LD_DYLIB_INSTALL_NAME'] = '@rpath/${EXECUTABLE_PATH}'
        target.build_settings(configuration.name)['LD_RUNPATH_SEARCH_PATHS'] = [
          '$(inherited)',
          '@rpath', 
          '@loader_path/Frameworks'
        ].join(' ')

        target.build_settings(configuration.name)['HEADER_SEARCH_PATHS'] = [
          "$(inherited)", "${PODS_ROOT}/Headers/**",
          "$(SRCROOT)/../../../React/**",
          "$(SRCROOT)/../../../react-native/React/**"
        ].join(' ')

        target.build_settings(configuration.name)['OTHER_LDFLAGS'] = "$(inherited) -undefined dynamic_lookup"
      end
    end
  end
end
