# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'OAuthManager' do
  # podspec :path => "./OAuthManager.podspec"

  # Pods for OauthManager
  pod 'OAuthSwift', '~> 0.5.2'
  #
  #
  # post_install do |installer|
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       cflags = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
  #       # cflags << '-fembed-bitcode'
  #       config.build_settings['OTHER_CFLAGS'] = cflags
  #     end
  #   end
  # end
end
